### PR TITLE
Empty file upload fix

### LINKED ISSUE #2778: Cannot upload empty file or blank file field
**Preconditions:**
- Swoole 4.x (any version)

**Steps to reproduce:**
1. Create a simple Swoole server that responds with uploaded files:
    ```php
    $server = new \Swoole\Http\Server('127.0.0.1', 8180);
    $server->on('request', function ($request, $response) {
        $response->header('Content-Type', 'text/plain');
        $response->end(var_export($request->files, true));
    });
    $server->start();
    ```
2. Create simple HTML form with file upload fields, for example:
    ```html
    <!DOCTYPE html>
    <html>
    <body>
        <form action="http://127.0.0.1:8180/" method="post" enctype="multipart/form-data">
            <input type="file" name="file1"><br>
            <input type="file" name="file2"><br>
            <input type="file" name="file3"><br>
            <input type="submit" value="Upload">
        </form>
    </body>
    </html>
    ```
3. Open the file upload form in a browser
4. Select _non-empty file_ for field `file1`
5. Select _empty file_ for field `file2`
6. Leave _blank value_ for field `file3`
7. Submit the form

**Alternative steps to reproduce:**
1. Upload files form data:
    ```bash
    curl http://127.0.0.1:8180/ \
        -F 'file1=@shipping_rates.csv;type=text/csv' \
        -F 'file2=@/dev/null;filename=empty.txt;type=text/plain' \
        -F 'file3=@/dev/null;filename=' \
    ```

**Expected result:**
- Non-empty file has been uploaded successfully
- Empty file has been uploaded successfully with zero size
- Blank file field has empty upload metadata temp filename and MIME type
    ```php
    array (
      'file1' => 
      array (
        'name' => 'shipping_rates.csv',
        'type' => 'text/csv',
        'tmp_name' => '/tmp/swoole.upfile.NxKEmB',
        'error' => 0,
        'size' => 2469,
      ),
      'file2' => 
      array (
        'name' => 'empty.txt',
        'type' => 'text/plain',
        'tmp_name' => '/tmp/swoole.upfile.hllJL5',
        'error' => 0,
        'size' => 0,
      ),
      'file3' => 
      array (
        'name' => '',
        'type' => '',
        'tmp_name' => '',
        'error' => 4,
        'size' => 0,
      ),
    )
    ```

**Actual result:**
- Non-empty file has been uploaded successfully
- Empty file has been uploaded with error `HTTP_UPLOAD_ERR_NO_FILE = 4`
- Blank file field has irrelevant temp filename and MIME type metadata
    ```php
    array (
      'file1' => 
      array (
        'name' => 'shipping_rates.csv',
        'type' => 'text/csv',
        'tmp_name' => '/tmp/swoole.upfile.NxKEmB',
        'error' => 0,
        'size' => 2469,
      ),
      'file2' => 
      array (
        'name' => 'empty.txt',
        'type' => 'text/plain',
        'tmp_name' => '/tmp/swoole.upfile.hllJL5',
        'error' => 4,
        'size' => 0,
      ),
      'file3' => 
      array (
        'name' => '',
        'type' => 'application/octet-stream',
        'tmp_name' => '/tmp/swoole.upfile.Gv03qi',
        'error' => 4,
        'size' => 0,
      ),
    )
    ```

### PR DESCRIPTION
**Pull request by sshymko**
- Distinguish blank file field from empty file contents
- Fix upload of file with empty contents of zero length
- Prevent empty temp file creation for blank file field
- Remove irrelevant MIME type of blank file field
- Resolve #2778 Cannot upload empty file or blank file field

### CODE REVIEW

File: swoole_http_request.cc [hunk 1]
```diff
@@ -696,10 +699,6 @@ static int multipart_body_on_data_end(multipart_parser* p)
     {
         long size = swoole_file_get_size((FILE *) p->fp);
         add_assoc_long(z_multipart_header, "size", size);
-        if (size == 0)
-        {
-            add_assoc_long(z_multipart_header, "error", HTTP_UPLOAD_ERR_NO_FILE);
```
Comment (sshymko) [inline swoole_http_request.cc]: Allow legitimate upload of empty file with zero contents not to be confused with blank form field.

File: swoole_http_request.cc [hunk 2]
```diff
@@ -560,17 +560,20 @@ static int multipart_body_on_header_value(multipart_parser* p, const char *at, s
             tmp = http_trim_double_quote(value_buf, &value_len);
 
             add_assoc_stringl(z_multipart_header, "name", tmp, value_len);
+            if (value_len == 0)
```
Comment (sshymko) [inline swoole_http_request.cc]: Empty filename indicates blank file field.

**Comment by sshymko** [comment]
Tests should cover both blank file field and legitimate upload of file with empty contents.
